// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/currency/v1/currency.proto

package currencyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение для представления валюты
type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_api_proto_currency_v1_currency_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Запросы для создания валюты
type CreateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyType  string                 `protobuf:"bytes,1,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCurrencyRequest) Reset() {
	*x = CreateCurrencyRequest{}
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurrencyRequest) ProtoMessage() {}

func (x *CreateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*CreateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_currency_v1_currency_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCurrencyRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *CreateCurrencyRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CreateCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCurrencyResponse) Reset() {
	*x = CreateCurrencyResponse{}
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurrencyResponse) ProtoMessage() {}

func (x *CreateCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurrencyResponse.ProtoReflect.Descriptor instead.
func (*CreateCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_currency_v1_currency_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCurrencyResponse) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *CreateCurrencyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запросы для получения валюты по ID
type GetCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyType  string                 `protobuf:"bytes,1,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyRequest) Reset() {
	*x = GetCurrencyRequest{}
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyRequest) ProtoMessage() {}

func (x *GetCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyRequest.ProtoReflect.Descriptor instead.
func (*GetCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_currency_v1_currency_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrencyRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *GetCurrencyRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyResponse) Reset() {
	*x = GetCurrencyResponse{}
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyResponse) ProtoMessage() {}

func (x *GetCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyResponse.ProtoReflect.Descriptor instead.
func (*GetCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_currency_v1_currency_proto_rawDescGZIP(), []int{4}
}

func (x *GetCurrencyResponse) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

// Запросы для получения всех валют типа
type GetCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyType  string                 `protobuf:"bytes,1,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrenciesRequest) Reset() {
	*x = GetCurrenciesRequest{}
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrenciesRequest) ProtoMessage() {}

func (x *GetCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*GetCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_currency_v1_currency_proto_rawDescGZIP(), []int{5}
}

func (x *GetCurrenciesRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

type GetCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*Currency            `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrenciesResponse) Reset() {
	*x = GetCurrenciesResponse{}
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrenciesResponse) ProtoMessage() {}

func (x *GetCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*GetCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_currency_v1_currency_proto_rawDescGZIP(), []int{6}
}

func (x *GetCurrenciesResponse) GetCurrencies() []*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

// Запросы для обновления валюты
type UpdateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyType  string                 `protobuf:"bytes,1,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCurrencyRequest) Reset() {
	*x = UpdateCurrencyRequest{}
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrencyRequest) ProtoMessage() {}

func (x *UpdateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*UpdateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_currency_v1_currency_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCurrencyRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *UpdateCurrencyRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCurrencyRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCurrencyResponse) Reset() {
	*x = UpdateCurrencyResponse{}
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrencyResponse) ProtoMessage() {}

func (x *UpdateCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrencyResponse.ProtoReflect.Descriptor instead.
func (*UpdateCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_currency_v1_currency_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCurrencyResponse) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *UpdateCurrencyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запросы для удаления валюты
type DeleteCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyType  string                 `protobuf:"bytes,1,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCurrencyRequest) Reset() {
	*x = DeleteCurrencyRequest{}
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurrencyRequest) ProtoMessage() {}

func (x *DeleteCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurrencyRequest.ProtoReflect.Descriptor instead.
func (*DeleteCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_currency_v1_currency_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCurrencyRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *DeleteCurrencyRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCurrencyResponse) Reset() {
	*x = DeleteCurrencyResponse{}
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurrencyResponse) ProtoMessage() {}

func (x *DeleteCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_currency_v1_currency_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurrencyResponse.ProtoReflect.Descriptor instead.
func (*DeleteCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_currency_v1_currency_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCurrencyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_currency_v1_currency_proto protoreflect.FileDescriptor

const file_api_proto_currency_v1_currency_proto_rawDesc = "" +
	"\n" +
	"$api/proto/currency/v1/currency.proto\x12\vcurrency.v1\"X\n" +
	"\bCurrency\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"R\n" +
	"\x15CreateCurrencyRequest\x12#\n" +
	"\rcurrency_type\x18\x01 \x01(\tR\fcurrencyType\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"e\n" +
	"\x16CreateCurrencyResponse\x121\n" +
	"\bcurrency\x18\x01 \x01(\v2\x15.currency.v1.CurrencyR\bcurrency\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x12GetCurrencyRequest\x12#\n" +
	"\rcurrency_type\x18\x01 \x01(\tR\fcurrencyType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"H\n" +
	"\x13GetCurrencyResponse\x121\n" +
	"\bcurrency\x18\x01 \x01(\v2\x15.currency.v1.CurrencyR\bcurrency\";\n" +
	"\x14GetCurrenciesRequest\x12#\n" +
	"\rcurrency_type\x18\x01 \x01(\tR\fcurrencyType\"N\n" +
	"\x15GetCurrenciesResponse\x125\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2\x15.currency.v1.CurrencyR\n" +
	"currencies\"b\n" +
	"\x15UpdateCurrencyRequest\x12#\n" +
	"\rcurrency_type\x18\x01 \x01(\tR\fcurrencyType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\"e\n" +
	"\x16UpdateCurrencyResponse\x121\n" +
	"\bcurrency\x18\x01 \x01(\v2\x15.currency.v1.CurrencyR\bcurrency\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x15DeleteCurrencyRequest\x12#\n" +
	"\rcurrency_type\x18\x01 \x01(\tR\fcurrencyType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"2\n" +
	"\x16DeleteCurrencyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xcc\x03\n" +
	"\x0fCurrencyService\x12Y\n" +
	"\x0eCreateCurrency\x12\".currency.v1.CreateCurrencyRequest\x1a#.currency.v1.CreateCurrencyResponse\x12P\n" +
	"\vGetCurrency\x12\x1f.currency.v1.GetCurrencyRequest\x1a .currency.v1.GetCurrencyResponse\x12V\n" +
	"\rGetCurrencies\x12!.currency.v1.GetCurrenciesRequest\x1a\".currency.v1.GetCurrenciesResponse\x12Y\n" +
	"\x0eUpdateCurrency\x12\".currency.v1.UpdateCurrencyRequest\x1a#.currency.v1.UpdateCurrencyResponse\x12Y\n" +
	"\x0eDeleteCurrency\x12\".currency.v1.DeleteCurrencyRequest\x1a#.currency.v1.DeleteCurrencyResponseB0Z.OtusGo/internal/grpc/pb/currency/v1;currencyv1b\x06proto3"

var (
	file_api_proto_currency_v1_currency_proto_rawDescOnce sync.Once
	file_api_proto_currency_v1_currency_proto_rawDescData []byte
)

func file_api_proto_currency_v1_currency_proto_rawDescGZIP() []byte {
	file_api_proto_currency_v1_currency_proto_rawDescOnce.Do(func() {
		file_api_proto_currency_v1_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_currency_v1_currency_proto_rawDesc), len(file_api_proto_currency_v1_currency_proto_rawDesc)))
	})
	return file_api_proto_currency_v1_currency_proto_rawDescData
}

var file_api_proto_currency_v1_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_currency_v1_currency_proto_goTypes = []any{
	(*Currency)(nil),               // 0: currency.v1.Currency
	(*CreateCurrencyRequest)(nil),  // 1: currency.v1.CreateCurrencyRequest
	(*CreateCurrencyResponse)(nil), // 2: currency.v1.CreateCurrencyResponse
	(*GetCurrencyRequest)(nil),     // 3: currency.v1.GetCurrencyRequest
	(*GetCurrencyResponse)(nil),    // 4: currency.v1.GetCurrencyResponse
	(*GetCurrenciesRequest)(nil),   // 5: currency.v1.GetCurrenciesRequest
	(*GetCurrenciesResponse)(nil),  // 6: currency.v1.GetCurrenciesResponse
	(*UpdateCurrencyRequest)(nil),  // 7: currency.v1.UpdateCurrencyRequest
	(*UpdateCurrencyResponse)(nil), // 8: currency.v1.UpdateCurrencyResponse
	(*DeleteCurrencyRequest)(nil),  // 9: currency.v1.DeleteCurrencyRequest
	(*DeleteCurrencyResponse)(nil), // 10: currency.v1.DeleteCurrencyResponse
}
var file_api_proto_currency_v1_currency_proto_depIdxs = []int32{
	0,  // 0: currency.v1.CreateCurrencyResponse.currency:type_name -> currency.v1.Currency
	0,  // 1: currency.v1.GetCurrencyResponse.currency:type_name -> currency.v1.Currency
	0,  // 2: currency.v1.GetCurrenciesResponse.currencies:type_name -> currency.v1.Currency
	0,  // 3: currency.v1.UpdateCurrencyResponse.currency:type_name -> currency.v1.Currency
	1,  // 4: currency.v1.CurrencyService.CreateCurrency:input_type -> currency.v1.CreateCurrencyRequest
	3,  // 5: currency.v1.CurrencyService.GetCurrency:input_type -> currency.v1.GetCurrencyRequest
	5,  // 6: currency.v1.CurrencyService.GetCurrencies:input_type -> currency.v1.GetCurrenciesRequest
	7,  // 7: currency.v1.CurrencyService.UpdateCurrency:input_type -> currency.v1.UpdateCurrencyRequest
	9,  // 8: currency.v1.CurrencyService.DeleteCurrency:input_type -> currency.v1.DeleteCurrencyRequest
	2,  // 9: currency.v1.CurrencyService.CreateCurrency:output_type -> currency.v1.CreateCurrencyResponse
	4,  // 10: currency.v1.CurrencyService.GetCurrency:output_type -> currency.v1.GetCurrencyResponse
	6,  // 11: currency.v1.CurrencyService.GetCurrencies:output_type -> currency.v1.GetCurrenciesResponse
	8,  // 12: currency.v1.CurrencyService.UpdateCurrency:output_type -> currency.v1.UpdateCurrencyResponse
	10, // 13: currency.v1.CurrencyService.DeleteCurrency:output_type -> currency.v1.DeleteCurrencyResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_currency_v1_currency_proto_init() }
func file_api_proto_currency_v1_currency_proto_init() {
	if File_api_proto_currency_v1_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_currency_v1_currency_proto_rawDesc), len(file_api_proto_currency_v1_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_currency_v1_currency_proto_goTypes,
		DependencyIndexes: file_api_proto_currency_v1_currency_proto_depIdxs,
		MessageInfos:      file_api_proto_currency_v1_currency_proto_msgTypes,
	}.Build()
	File_api_proto_currency_v1_currency_proto = out.File
	file_api_proto_currency_v1_currency_proto_goTypes = nil
	file_api_proto_currency_v1_currency_proto_depIdxs = nil
}
